Update to absolute file paths
Rinchem-ChemStar/IntelInventoryExport pull request #2
Opened 2021-06-21 18:37 UTC by Chem-Star

Updated the path to certain file operations to use absolute file paths defined in appsettings. This allows greater flexibility when deploying to the server.
Add environment specific appsettings to configuration.
White space changes due to auto formatting on save.

2021-06-21 23:01 UTC, eddieSkywalker90 commented on IntelInventory/src/Configuration.cs
> +            ;
Extra unused semi-colon by itself

2021-06-21 23:53 UTC, eddieSkywalker90 commented on IntelInventory/appsettings.json
>    "Properties": {
Unless you see a need to keep the Properties section, I didn't actually end up using this entire section. . I just took the to and from locations that were used and put them under the FTP config section. Unless you see reason to keep Properties section we should remove.

2021-06-21 23:54 UTC, eddieSkywalker90 requested changes
Write 2 comments on appsettings.json + Configuration.cs. Neither are functional issues, just cosmetic.

2021-06-22 14:36 UTC, Chem-Star commented on IntelInventory/src/Configuration.cs
> +            ;
Removed.

2021-06-22 14:36 UTC, Chem-Star commented on IntelInventory/appsettings.json
>    "Properties": {
Agreed, removed.

2021-06-22 16:08 UTC, merged